server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info,health

info:
  application:
    name:             @project.build.finalName@
    version:          @project.version@
    build-timestamp:  @maven.build.timestamp@
